---
name: "tagged-release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  create-tagged-release:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build signed APK
        uses: r0adkll/sign-android-release@v1
        id: sign
        with:
          releaseDirectory: ./
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{ steps.sign.signedReleaseFile }}
